name: SSH & Install Docker

on:
  workflow_dispatch:

jobs:
  install-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH and install Docker
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.EC2_PUBLIC_IP }}   # Use the EC2 IP from deploy pipeline output or manual input
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            chmod +x /home/ubuntu/scripts/install_docker.sh
            /home/ubuntu/scripts/install_docker.sh