name: SSH & Install Docker

on:
  workflow_dispatch:
    inputs:
      ec2_ip:
        description: 'Public IP of EC2 instance'
        required: true

jobs:
  install-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH and install Docker
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ github.event.inputs.ec2_ip }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            chmod +x /home/ubuntu/scripts/install_docker.sh
            /home/ubuntu/scripts/install_docker.sh